name: Just another test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout latest code
        uses: actions/checkout@316b28ccf6b2cd2e791db4ec8842dda6817e48f1 # testing from
        with:
          persist-credentials: false
      