name: Build and push to Docker HUB

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: jksolbakken/jktest

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Generate Docker image tag with short sha
        id: dockertag
        run: |
          echo "current_tag=${{ env.IMAGE_NAME }}:$(git rev-parse --short HEAD)" >> ${GITHUB_OUTPUT}
          echo "latest_tag=${{ env.IMAGE_NAME }}:latest" >> ${GITHUB_OUTPUT}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          pull: true
          push: true
          tags: ${{ steps.dockertag.outputs.current_tag }},${{ steps.dockertag.outputs.latest_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


