name: manual

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: test
    steps:
      - name: Nothing to see here
        run: |
          echo "doing stuff"

