name: manual triggering

on:
  workflow_dispatch:

permissions: {}

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: test
    steps:
      - name: Test onbuild detector action
        uses: navikt/onbuild-check@v1.20260528122012
        with:
          mode: enforce

