name: manual

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Nothing to see here
        if: ${{ github.actor }} == 'jksolbakken'
        run: |
          ALL_ENVS=$(env)
          echo $ALL_ENVS

  