name: manual

on:
  workflow:dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Do JK stuff
        if: github.event.pull_request.user.login == 'jksolbakken'
        run: |
          ALL_ENVS=$(env)
          echo $ALL_ENVS

  