name: PR stuff

on:
  pull_request:

env:
  myvar: myvalue

jobs:
  first_job:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      opkey: opval
    steps:
      - name: Checkout latest code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
        with:
          persist-credentials: false
      - name: Do other stuff
        run: |
          echo "head_ref: ${{ head_ref }}"
          echo "ref: ${{ ref }}"
        env:
          head_ref: ${{ github.head_ref }}"
          ref: ${{ github.ref }}"

