name: PR workflow

on:
  pull_request:
    types:
      - opened
      - edited
    
env:
  myvar: myvalue

jobs:
  first_job:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout latest code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # ratchet:actions/checkout@v3
        with:
          persist-credentials: false
      - name: Important build stuff 
        run: |
          echo "Building PR: ${{ github.event.pull_request.title }}"
          echo "testing"
        env:
          SUPERSECRET: ${{ secrets.BOGUS }}

