name: PR stuff

on:
  pull_request:

env:
  myvar: myvalue

jobs:
  first_job:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      opkey: opval
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Do other stuff
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"
  