name: Play around with stuff

on:
  workflow_dispatch:

env:
  myvar: myvalue

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Do other stuff
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"

  second_job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: do second_job_thing
        if: ${{ env.THE_TOKEN != '' }}
        run: echo "hello from second job, token exists"
    env:
      THE_TOKEN: ${{ secrets.GITHUB_TOKEN}}

  third_job:
    runs-on: ubuntu-latest
    if: ${{ NONEXISTING != '' }}
    steps:
      - name: do third_job_thing
        run: echo "hello from third job, env exists"


