name: Play around with stuff

on:
  workflow_dispatch:
    inputs:
      thing:
        description: Please input thing
        type: string

env:
  myvar: myvalue

jobs:
  first_job:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      opkey: opval
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Do stuff
        run: echo "it is oci://$myvar/other-stuff"
      - name: Do other stuff
        run: echo "but does it work like this? ${{ env.myvar }}"
  
  second_job:
    runs-on: ubuntu-22.04
    needs: 
      - first_job
    steps:
      - name: thestep
        run: 'echo "From first_job: ${{ needs.first_job.outputs.opkey }}"'

  third_job:
    runs-on: ubuntu-22.04
    needs: 
      - first_job
      - second_job
    steps:
      - name: thestep
        run: 'echo "From first_job: ${{ needs.first_job.outputs.opkey }}"'
      - name: thing
        run: echo ${{ github.head_ref }}

  fourth_job:
    runs-on: ubuntu-22.04
    env:
        envstuff: ${{ github.event.inputs.thing }}
    steps:
      - name: Script injection fun
        run: |
          inlinestuff="${{ github.event.inputs.thing }}"
          secondinlinestuff="${{ github.event.inputs.thing }}"
          echo "your unfiltered input was $inlinestuff"
          echo "your filtered input was $envstuff"
