name: Play around with stuff

on:
  workflow_dispatch:
    inputs:
      thing:
        description: Please input thing
        type: string

env:
  myvar: myvalue

jobs:
  first_job:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    outputs:
      opkey: opval
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@v2
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            www.vg.no:443
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Do stuff
        run: echo "it is oci://$myvar/other-stuff"
      - name: Do other stuff
        run: echo "but does it work like this? ${{ env.myvar }}"
      - name: Egress to VG is allowed
        run: curl -i https://www.vg.no
      - name: Sudo should be blocked
        run: sudo ls
  
  second_job:
    runs-on: ubuntu-22.04
    needs: 
      - first_job
    steps:
      - name: thestep
        run: 'echo "From first_job: ${{ needs.first_job.outputs.opkey }}"'

  third_job:
    runs-on: ubuntu-22.04
    needs: 
      - first_job
      - second_job
    steps:
      - name: thestep
        run: 'echo "From first_job: ${{ needs.first_job.outputs.opkey }}"'

  fourth_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Script injection fun
        run: |
          echo "your input was ${{ github.event.inputs.thing }}"
