name: yolo

on:
  pull_request:
    branches:
      - main


jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Do JK stuff
        if: github.event.pull_request.user.login == 'jksolbakken'
        run: |
          echo "J-K, ja"
      - name: Do stuff other user
        if: github.event.pull_request.user.login != 'jksolbakken'
        run: |
          echo "Ikke J-K, men $THEUSER"
        env:
          THEUSER: ${github.event.pull_request.user.login}

  