name: yolo

on:
  workflow_dispatch:


jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "use my action"
        uses: jksolbakken/tulleaction@v1.1

  