name: yolo

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Do other stuff
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"

  second_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      creds_present: ${{ steps.second_job_thing.outputs.CREDS_PRESENT }}
    steps:
      - name: do second_job_thing
        id: second_job_thing
        if: ${{ env.THETOKEN != '' }}
        run: |
          echo "hello from second job, token exists"
          echo "CREDS_PRESENT=${{ secrets.GITHUB_TOKEN != ''}}" >> $GITHUB_OUTPUT
    env:
      THETOKEN: ${{ secrets.GITHUB_TOKEN }}

  third_job:
    runs-on: ubuntu-latest
    needs: [second_job]
    if: ${{ needs.second_job.outputs.creds_present }}
    permissions:
      contents: read
    steps:
      - name: do third_job_thing
        if: ${{ env.NONEXISTING == '' }}
        run: |
          echo "hello from third job, env is missing"
          echo "output from second job: ${{ needs.second_job.outputs.creds_present }}"

